### ISSUE TITLE
Welcome Mail template: Username and Password fields must be changed

### ISSUE THREAD

**Issue by optitsolutions** [humhub/massuserimport-issues#14]
### What steps will reproduce the problem?
adding a new user (auto-created welcome mail)
### What is the expected result?
correct fields in welcome mail template
### What do you get instead?
wrong fields in welcome mail.
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | newest
| PHP version      | 8.x
| Operating system | 

example (german):

"... Dein Nutzerkonto wurde bereits erstellt. Die Logindaten lauten:

Passwort: testuser1
Nutzername: dummyPassword
..."

**Comment by luke-** [comment]
The issue is regarding the MassUserImport module?

**Comment by optitsolutions** [comment]
sorry, you're right.

**Comment by luke-** [comment]
@optitsolutions No problem, I've moved it.

**Comment by yurabakhtin** [comment]
@luke- I cannot find the issue:

![email-welcome-massuserimport](https://github.com/humhub/massuserimport-issues/assets/6995524/97c6dced-9220-4581-9a9a-c74d589385e2)

I see here https://github.com/humhub/massuserimport/blob/master/views/mails/ImportUser.php#L138 we have code:

- `<?php echo Yii::t('MassuserimportModule.base', 'Username: %userName%.', array('%userName%' => Html::encode($model->user->username))); ?>`
- `<?php echo Yii::t('MassuserimportModule.base', 'Password: %password%.', array('%password%' => Html::encode($model->password->newPassword))); ?>`

i.e. we cannot have an error in the lines.

Probably errors are in the translations https://github.com/humhub/massuserimport/blob/master/messages/de/base.php#L49:

- `'Password: %password%.' => 'Passwort: %password%',`
- `'Username: %userName%.' => 'Benutzername: %userName%',`

I guess some language has errors in the lines, but I cannot find in the latest version, maybe the lines were updates by module "Translation Manager".

**Comment by optitsolutions** [comment]
I found it:
In the messages/de/base.php file:
...
'Password: %password%.' => 'Nutzername: %password%',
...
'Username: %userName%.' => 'Passwort: %userName%',
...

**Comment by yurabakhtin** [comment]
@optitsolutions Thanks for the info.
I see the errors were fixed here https://github.com/humhub/massuserimport/commit/33ade8c#diff-90763a4f570c05f657f748efe173468e8cdc97d778964fe63d67da38da151e8dR49
It will be fixed in next version `1.2.2`

@luke- I think we can release new version with these fixes, please confirm.

**Comment by luke-** [comment]
@yurabakhtin Yes, please release!

**Comment by yurabakhtin** [comment]
@luke- Done https://github.com/humhub/massuserimport/releases/tag/v1.2.2
