### ISSUE TITLE
Partial Translation During User and Password Email Sending

### ISSUE THREAD

**Issue by visbran** [humhub/massuserimport-issues#16]
Hello, the plugin works perfectly during bulk import; however, the content of the email sent is not entirely translated into French. Only the subject and the footer are translated; the content itself remains in English. What should I do? I've filled in the user.language and profile.country fields correctly.
![bug](https://github.com/humhub/massuserimport-issues/assets/19782373/5a2b040a-3bce-4b8f-b6b2-01028d605368)

**Comment by luke-** [comment]
@visbran You can contribute to community translations like French using our Translation Community: https://translate.humhub.org

**Comment by visbran** [comment]
> @visbran You can contribute to community translations like French using our Translation Community: https://translate.humhub.org

Thanks !
