### ISSUE TITLE
Period present in password when sending mail

### ISSUE THREAD

**Issue by visbran** [humhub/massuserimport-issues#18]
Hello, 

I noticed that when sending the email during account creation, at the end of the password there is a period to indicate the end of the phase, however, this period is confusing because it is not part of the password and users are therefore unable to log in.

![image](https://github.com/user-attachments/assets/ab2cc5f5-ac69-4675-9d15-02c4c29c60c2)

how can we remove this period? thank you in advance.

**Comment by marc-farre** [comment]
@luke- PR https://github.com/humhub/massuserimport/pull/28
I removed the ending dot in these 2 translations:
- 'Username: %userName%'
- 'Password: %password%'

I haven't done a `php yii message/extract-module massuserimport` (if I remember well, it's done automatically?)

**Comment by luke-** [comment]
@marc-farre Thanks.

Yes thanks `extract-module` run automatically, but in such cases it's good to fix existing translations manually. I've done this here:
https://github.com/humhub/massuserimport/pull/28/commits/1736f508240fc40ab1ece94910a51b4fb46b4c3d

**Comment by luke-** [comment]
Version 1.2.5 fixes this issue.
