### ISSUE TITLE
(timeout-?)Errors during import of well formed files

### ISSUE THREAD

**Issue by optitsolutions** [humhub/massuserimport-issues#6]
When I import an import file of 4 or more records, I regularly get response 500 (internal server error) - probably script runtime error.
Random data records are imported, usually between 2 and 9, tested with 10 files and two different installations. The import runs for about 30 or 40 seconds per record (!).

**Comment by luke-** [comment]
There must be somewhere a more detailed error message for the Internal Server Errors. This can be found either in the HumHub log or in the webserver/PHP logs.

Can you please post this message?

**Comment by optitsolutions** [comment]
@luke- the answer from humhub is: "The server encountered an internal error or misconfiguration and was unable to complete your request"

here the only corresponding log entry. It is exact the same issue on two installations:

PDOException: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction in /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('UPDATE `queue` ...')
#2 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(250): yii\db\Command->execute()
#3 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(182): yii\queue\db\Queue->moveExpired()
#4 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}(Object(yii\db\Connection))
#5 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/db/Connection.php(1129): call_user_func(Object(Closure), Object(yii\db\Connection))
#6 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(212): yii\db\Connection->useMaster(Object(Closure))
#7 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(78): yii\queue\db\Queue->reserve()
#8 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}(Object(Closure))
#9 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure))
#10 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93): yii\queue\cli\Queue->runWorker(Object(Closure))
#11 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run(false)
#12 [internal function]: yii\queue\db\Command->actionRun()
#13 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#15 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('run', Array)
#16 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('run', Array)
#17 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/run', Array)
#18 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/run', Array)
#19 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(yii\console\Request))
#20 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/yii(29): yii\base\Application->run()
#21 {main}

Next yii\db\Exception: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
The SQL being executed was: UPDATE `queue` SET `reserved_at`=NULL WHERE `reserved_at` is not null and `reserved_at` < 1660550580 - `ttr` and `done_at` is null in /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/db/Schema.php:676
Stack trace:
#0 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'UPDATE `queue` ...')
#1 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('UPDATE `queue` ...')
#2 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(250): yii\db\Command->execute()
#3 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(182): yii\queue\db\Queue->moveExpired()
#4 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}(Object(yii\db\Connection))
#5 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/db/Connection.php(1129): call_user_func(Object(Closure), Object(yii\db\Connection))
#6 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(212): yii\db\Connection->useMaster(Object(Closure))
#7 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(78): yii\queue\db\Queue->reserve()
#8 [internal function]: yii\queue\db\Queue->yii\queue\db\{closure}(Object(Closure))
#9 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure))
#10 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Queue.php(93): yii\queue\cli\Queue->runWorker(Object(Closure))
#11 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2-queue/src/drivers/db/Command.php(56): yii\queue\db\Queue->run(false)
#12 [internal function]: yii\queue\db\Command->actionRun()
#13 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#15 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('run', Array)
#16 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('run', Array)
#17 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/run', Array)
#18 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('queue/run', Array)
#19 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(yii\console\Request))
#20 /usr/local/www/apache24/data/intranet.xyz.de/humhub/protected/yii(29): yii\base\Application->run()
#21 {main}
Additional Information:
Array
(
[0] => HY000
[1] => 1205
[2] => Lock wait timeout exceeded; try restarting transaction
)

**Comment by optitsolutions** [comment]
each new record needs about 30-50 seconds and leeds into a timeout.

**Comment by optitsolutions** [comment]
fixed some months ago
